name: Repack

on:
  push:
    paths:
      - repack.sh
      - .github/workflows/repack.yml
  workflow_dispatch: ~
  schedule:
    - cron: "30 22 * * *"

jobs:
  repack:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Set up Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'

      - name: Checkout
        uses: actions/checkout@v3

      - name: Force renew if triggered by push event or workflow dispatch
        if: ${{ github.event_name == 'workflow_dispatch' || github.event_name == 'push' }}
        run: echo > .source.lock

      - name: Repack
        run: sh repack.sh

      - name: Check worktree
        id: check_worktree
        run: |
          echo "::set-output name=tag::v$(cat .source.lock | head -n 1)"
          if [ -z "$(git status --porcelain)" ]; then
            echo '::set-output name=clean::true'
          else 
            echo '::set-output name=clean::false'
          fi

      - name: Commit and push
        if: ${{ steps.check_worktree.outputs.clean == 'false' }}
        run: |
          git add -A
          git commit -m '${{ steps.check_worktree.outputs.tag }}'
          git push

      - name: Tag and push
        if: ${{ steps.check_worktree.outputs.clean == 'false' || github.event_name == 'workflow_dispatch' || github.event_name == 'push' }}
        run: |
          git tag -f '${{ steps.check_worktree.outputs.tag }}'
          git push -f --tags

      - name: Fetch changelog
        if: ${{ steps.check_worktree.outputs.clean == 'false' || github.event_name == 'workflow_dispatch' || github.event_name == 'push' }}
        run: |
          rm -f build/CHANGELOG.html
          
          echo '<details><summary><h1>CHN Changelog</h1></summary>' > build/CHANGELOG.html
          echo >> build/CHANGELOG.html
          curl -sL 'https://linux.wps.cn/wpslinuxlog' | \
            grep -Pzo '(?<=<div class="log_main">)[\s\S]*?(?=\s*</div>)' | \
            head --bytes=-1 >> build/CHANGELOG.html
          echo >> build/CHANGELOG.html
          echo '</details>' >> build/CHANGELOG.html
          
          echo >> build/CHANGELOG.html
          
          echo '<details><summary><h1>INT Changelog</h1></summary>' >> build/CHANGELOG.html
          echo >> build/CHANGELOG.html
          curl -sL 'https://www.wps.com/whatsnew/linux/' | \
            grep -Pzo '<div class="nuxt-content"[^>]*>[\s\S]*?</div>' | \
            head --bytes=-1 >> build/CHANGELOG.html
          echo >> build/CHANGELOG.html
          echo '</details>' >> build/CHANGELOG.html

          sed -i 's/^[ \t]*//g' build/CHANGELOG.html
          echo >> build/CHANGELOG.html

      - uses: ncipollo/release-action@v1
        if: ${{ steps.check_worktree.outputs.clean == 'false' || github.event_name == 'workflow_dispatch' || github.event_name == 'push' }}
        with:
          allowUpdates: true
          artifactErrorsFailBuild: true
          artifacts: 'build/dist/*.deb'
          bodyFile: 'build/CHANGELOG.html'
          replacesArtifacts: true
          tag: ${{ steps.check_worktree.outputs.tag }}
